// <auto-generated />
using System;
using Manga.Infrastructure.EntityFrameworkDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Manga.Infrastructure.EntityFrameworkDataAccess.Migrations
{
    [DbContext(typeof(MangaContext))]
    [Migration("20190616205140_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Manga.Domain.Accounts.Account", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<Guid>("CustomerId");

                b.HasKey("Id");

                b.ToTable("Account");
            });

            modelBuilder.Entity("Manga.Domain.Accounts.Credit", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<Guid>("AccountId");

                b.Property<double?>("Amount");

                b.Property<DateTime>("TransactionDate");

                b.HasKey("Id");

                b.ToTable("Credit");
            });

            modelBuilder.Entity("Manga.Domain.Accounts.Debit", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<Guid>("AccountId");

                b.Property<double?>("Amount");

                b.Property<DateTime>("TransactionDate");

                b.HasKey("Id");

                b.ToTable("Debit");
            });

            modelBuilder.Entity("Manga.Domain.Customers.Customer", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Name");

                b.Property<string>("SSN");

                b.HasKey("Id");

                b.ToTable("Customer");

                b.HasData(
                    new
                    {
                        Id = new Guid("197d0438-e04b-453d-b5de-eca05960c6ae"),
                            Name = "Manga.Domain.ValueObjects.Name",
                            SSN = "Manga.Domain.ValueObjects.SSN"
                    });
            });
#pragma warning restore 612, 618
        }
    }
}