version: '3.4'

services:
  nginx:
    volumes:
      - ../.docker/https/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ../.docker/https/localhost.key:/etc/ssl/private/localhost.key:ro
  accounts-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyCertificatePassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
      - PersistenceModule__DefaultConnection=Server=sql1;User Id=sa;Password=<YourStrong!Passw0rd>;Database=Accounts;
    volumes:
      - ../.docker/https:/https:ro
  identity-server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyCertificatePassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
    volumes:
      - ../.docker/https:/https:ro
  wallet-spa:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  sql1:
    environment:
        SA_PASSWORD: "<YourStrong!Passw0rd>"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"