//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to github/ivanpaulovich.
        /// </summary>
        internal static string ExternalUserID {
            get {
                return ResourceManager.GetString("ExternalUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to github/andrepaulovich.
        /// </summary>
        internal static string ExternalUserID1 {
            get {
                return ResourceManager.GetString("ExternalUserID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9084272C-C324-4ECE-8186-90AB47E2F308.
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D0923768-B6D5-4298-AF6F-4903A15553C0.
        /// </summary>
        internal static string UserId1 {
            get {
                return ResourceManager.GetString("UserId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ivan Paulovich.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andre Paulovich.
        /// </summary>
        internal static string UserName1 {
            get {
                return ResourceManager.GetString("UserName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8608179999.
        /// </summary>
        internal static string UserSSN {
            get {
                return ResourceManager.GetString("UserSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8408319999.
        /// </summary>
        internal static string UserSSN1 {
            get {
                return ResourceManager.GetString("UserSSN1", resourceCulture);
            }
        }
    }
}
