name: .NET Core

on: [push]

jobs:
  build_docker_image:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Database then Run Tests
      run: |
        docker pull mcr.microsoft.com/mssql/server:2017-latest
        docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=<YourStrong!Passw0rd>' -p 1433:1433 --name sql1 -d mcr.microsoft.com/mssql/server:2017-latest
        sleep 10
        docker exec -i sql1 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '<YourStrong!Passw0rd>' -Q 'ALTER LOGIN SA WITH PASSWORD="<YourNewStrong!Passw0rd>"'
        dotnet tool install --global dotnet-ef
        dotnet ef database update --project src/Infrastructure --startup-project src/Infrastructure
        dotnet build
        dotnet test
